pipeline {
    agent { label 'master' }
    stages {
        stage("gradle build") { 
            steps {
                script { 
                    sh "cd web-hello-world && gradle build"
                }
            }
        }
        stage("dd command") { 
            steps {
                script { 
                    sh "dd if=/dev/zero of=testfile bs=1024 count=102400"
                }
            }
        }
    }
    post {
        always {
            echo "doing cleanup"
            sh "echo rm -rf ${workspaces}"
        }
    }
}
