pipeline {
    agent { label 'master' }
    stages {
        stage("gradle build") { 
            steps {
                script { 
                    sh "cd web-hello-world && gradle build"
                }
            }
        }
        stage("dd command") { 
            steps {
                script { 
                    sh "dd if=/dev/zero of=testfile bs=1024 count=102400"
                }
            }
        }
    }
    /*
    post {
        always {
            sh """
                echo INFO Workspace cleanup
                rm -rf ${WORKSPACE}
            """
        }
    }*/
    post {
        cleanup{
            /* clean up our workspace */
            deleteDir()
            /* clean up tmp directory */
            dir("${workspace}\@tmp") {
                deleteDir()
            }
            /* clean up script directory */
            dir("${workspace}\@script") {
                deleteDir()
            }
        }
    }
}
